### ISSUE TITLE
V1.0.0 Checklist

### ISSUE THREAD

**Issue by andreespirela** [useverto/cache#5]
The version 1.0.0 of the cache repository will be going out this Friday. Here is the check list of things that need to be aligned before this takes place

**Before Friday:**
- [x] Disable automatic deployments in Heroku (if enabled) so when the 1.0.0 branch is merged into dev and master, it does not affect the current endpoints
- [x] Create cache hooks in the https://github.com/useverto/cace-interface
      Hooks will be used to invoke refreshing of a contract for different operations.
- [x] Obtain a list with all the contracts that are cached and will be wanted to be cached on Friday in order to make the new production environment stable and compatible with the current information
- [x] Create tickets of the endpoints and functionalities that will need to be updated in the verto interface.
- [x] Get a domain through Google domains for the new API. https://cloud.google.com/appengine/docs/standard/python/mapping-custom-domains https://support.google.com/domains/answer/6009957?hl=en

**On Friday:**
- [x] Start deployment at noon EST.
- [x] Connect service instance to the acquired domain
- [x] Prepare the [Cache Interface](https://github.com/useverto/cace-interface) to work with the new endpoint for things like hook.
- [x] Deploy Cache Interface in NPM.
- [x] In the Verto Interface, start migrating current endpoints to the new ones as well as making use of the cache interface.
